import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

export const getServerSideProps: GetServerSideProps = async (context) => {
  return { props: {}, redirect: { destination: "/home" } };
};

const Page: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to luma app</h1>
      </main>
      <footer></footer>
    </div>
  );
};

export default Page;
